app/app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

app_name = 'users'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('users.urls')),
]

app/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^index/$', views.UserListView.as_view(), name='index'),

    url(r'^detail/(?P<pk>[0-9]+)/$', 
        views.UserDetailView.as_view(), name='detail'),

    url(r'^add/$', views.add, name='add'),
]

app/users/models.py
from django.db import models

from django.utils import timezone

# Create your models here.
class User(models.Model):

    created = models.DateTimeField(default=timezone.now())

    modified = models.DateTimeField(default=timezone.now())
    
    first_name = models.CharField(max_length=256, blank=False, null=False)

    last_name = models.CharField(max_length=256, blank=False, null=False)

    email = models.CharField(max_length=256, blank=False, null=False)

    age = models.IntegerField(blank=True, null=True)

    def __str__(self):
        """ Sensible string representation of a user."""
        return "{0} {1} | {2}".format(self.first_name, self.last_name, 
                self.email)

    def save(self, *args, **kwargs):
        """ Add created_at and updated_at timestamps. """
        if not self.id:
            self.created = timezone.now()

        self.modified = timezone.now()

        return super(User, self).save(*args, **kwargs)

app/users/forms.py
from django import forms

class UserForm(forms.Form):

    first_name = forms.CharField(label='First Name', max_length=256)
    
    last_name = forms.CharField(label='Last Name', max_length=256)

    email = forms.EmailField(label='Email', max_length=256)

    age = forms.IntegerField(label='Age', min_value=18)

app/users/views.py
from django.http import Http404, HttpResponse

from django.shortcuts import redirect, render

from django.views.generic import DetailView, ListView

from .forms import UserForm

from .models import User

class UserListView(ListView):
    model = User
    template_name = 'users/index.html'

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)

        # In real life we'd retrieve this from the session.
        context['name'] = 'Adonis'
        
        return context

class UserDetailView(DetailView):
    model = User
    template_name = 'users/detail.html'

def add(request):

    if request.method == 'POST':

        form = UserForm(request.POST)

        if form.is_valid():
            # Create and save directly.

            User(
             first_name=form.cleaned_data['first_name'], 
             last_name=form.cleaned_data['last_name'],
             email=form.cleaned_data['email'],
             age=form.cleaned_data['age']).save()
        
            return redirect('users:index')

        else:
            # Render form with errors.
            return render(request, 'users/add.html', { 'form' : form })

    else:
        # If the user sends a GET request...

        context = { 'header' : 'GET', 'form' : UserForm() }

        return render(request, 'users/add.html', context)

app/users/templates/users/add.html
{% extends 'users/base.html' %}

{% block title %} Add {% endblock %}

{% block content %}

    <h1>Add a User.</h1>

    <hr>

    <form method="post" action="{% url 'users:add' %}">

      {% csrf_token %}

      {% for field in form %}
        <div class="form-group">
            {{ field.errors }}

            {{ field.label_tag }} {{ field }}
        </div>
      {% endfor %}

      <button type="submit" class="btn btn-primary">Submit</button>

    </form>

{% endblock %}

app/users/templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
  
    <meta charset="utf-8">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS, no JS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>
  <body>

    <div class="container">
      {% block content %} {% endblock %}
    </div>

  </body>
</html>

app/users/templates/users/detail.html
{% extends 'users/base.html' %}

{% block title %} Detail {% endblock %} 

{% block content %}

<h1>Welcome, {{ user.first_name }}.</h1>

    <hr>

<h5>Profile Information</h5>

<table class="table table-striped table-bordered">
    <tr>
        <td>First Name</td>
        <td>{{ user.first_name }}</td>
    </tr>

    <tr>
        <td>Last Name</td>
        <td>{{ user.last_name }}</td>
    </tr>

    <tr>
        <td>Email</td>
        <td>{{ user.email }}</td>
    </tr>

</table>

{% endblock %}

app/users/templates/users/index.html
{% extends 'users/base.html' %}

{% block title %} Index {% endblock %}

{% block content %}

  {% if name %}
    <h1>Hello, {{ name }}!</h1>
  {% else %}
    <h1>Hello, Stranger!</h1>
  {% endif %}

  {% if user_list %}
    <ul class="list-group">
    {% for user in user_list %} 
      <li class="list-group-item">{{ user }}</li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No users yet.</p>
  {% endif%}

{% endblock %}